from neopixel import Color
from time import sleep
from scene import Scene
import random

EYE = Color(32, 32, 0)
SKIN = Color(0, 20, 32)
BROWN = Color(0, 0, 16)
NOSE = Color(14, 0, 0)
# SKIN = Color(48, 32, 0)
# BROWN = Color(28, 16, 0)
NONE = Color(0, 0, 0)

FRAME1 = [
    [NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE],
    [NONE, NONE, NONE, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, NONE, NONE, SKIN, SKIN, SKIN, NONE],
    [NONE, NONE, NONE, NONE, NONE, NONE, NONE, SKIN, NONE, SKIN, NONE, NONE, SKIN, NONE, SKIN, NONE],
    [NONE, NONE, NONE, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, NONE, NONE, SKIN, SKIN, SKIN, NONE],
    [NONE, NONE, NONE, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, NONE, NONE, SKIN, SKIN, EYE, EYE, SKIN, EYE, EYE, SKIN, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, NONE, NONE, SKIN, SKIN, EYE, EYE, SKIN, EYE, EYE, SKIN, NONE],
    [NONE, SKIN, SKIN, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, NOSE, SKIN, SKIN, SKIN, NONE],
    [NONE, SKIN, SKIN, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, NOSE, SKIN, NOSE, SKIN, SKIN, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, NONE],
]

FRAME2 = [
    [NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE],
    [NONE, NONE, NONE, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, NONE, NONE, SKIN, SKIN, SKIN, NONE],
    [NONE, NONE, NONE, NONE, NONE, NONE, NONE, SKIN, NONE, SKIN, NONE, NONE, SKIN, NONE, SKIN, NONE],
    [NONE, NONE, NONE, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, NONE, NONE, SKIN, SKIN, SKIN, NONE],
    [NONE, NONE, NONE, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, NONE, NONE, SKIN, SKIN, EYE, EYE, SKIN, EYE, EYE, SKIN, NONE],
    [NONE, SKIN, SKIN, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, NOSE, SKIN, SKIN, SKIN, NONE],
    [NONE, SKIN, SKIN, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, NOSE, SKIN, NOSE, SKIN, SKIN, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, NONE],
]

FRAME3 = [
    [NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE],
    [NONE, NONE, NONE, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, NONE, NONE, SKIN, SKIN, SKIN, NONE],
    [NONE, NONE, NONE, NONE, NONE, NONE, NONE, SKIN, NONE, SKIN, NONE, NONE, SKIN, NONE, SKIN, NONE],
    [NONE, SKIN, SKIN, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, NONE, NONE, SKIN, SKIN, SKIN, NONE],
    [NONE, SKIN, SKIN, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE],
    [NONE, SKIN, SKIN, NONE, NONE, NONE, NONE, SKIN, SKIN, EYE, EYE, SKIN, EYE, EYE, SKIN, NONE],
    [NONE, SKIN, SKIN, NONE, NONE, NONE, NONE, SKIN, SKIN, EYE, EYE, SKIN, EYE, EYE, SKIN, NONE],
    [NONE, SKIN, SKIN, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, NOSE, SKIN, SKIN, SKIN, NONE],
    [NONE, SKIN, SKIN, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, NOSE, SKIN, NOSE, SKIN, SKIN, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, SKIN, SKIN, BROWN, BROWN, NONE, NONE, NONE],
]


class Cat(Scene):
    def show(self, frame):
        for x in range(16):
            for y in range(16):
                self._display.set_pixel(x, y, frame[y][x])
        self._display.draw()

    def iter(self):
        self.show(random.choice([FRAME1, FRAME2, FRAME3]))
        sleep(2)
