from neopixel import Color
from time import sleep
from scene import Scene

EYE = Color(32, 0, 0)
SKIN = Color(48, 32, 0)
NONE = Color(0, 0, 0)

FRAME1 = [
    [NONE, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE, NONE],
    [NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, EYE, EYE, SKIN, SKIN, SKIN, NONE, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, EYE, EYE, SKIN, SKIN, SKIN, NONE, NONE],
    [SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE],
    [SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE],
    [SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE],
    [SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE],
    [SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE],
    [NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE, NONE],
    [NONE, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE, NONE, NONE, NONE],
    [NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE],
]

FRAME2 = [
    [NONE, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE, NONE],
    [NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, EYE,  EYE,  SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, EYE,  EYE,  SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE, NONE],
    [SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE, NONE, NONE],
    [SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE, NONE, NONE, NONE],
    [SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE, NONE, NONE],
    [SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE],
    [NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE],
    [NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE, NONE],
    [NONE, NONE, NONE, NONE, NONE, SKIN, SKIN, SKIN, SKIN, SKIN, NONE, NONE, NONE, NONE, NONE, NONE],
    [NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE, NONE],
]


class PacMan(Scene):
    def show(self, frame):
        for x in range(16):
            for y in range(16):
                self._display.set_pixel(x, y, frame[y][x])
        self._display.draw()

    def iter(self):
        self.show(FRAME1)
        sleep(1)
        self.show(FRAME2)
        sleep(1)
